### ISSUE TITLE
Error BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### ISSUE THREAD

**Issue by mbs220** [lobe/lobe.NET#15]
hello everybody
i made a LOBE model as onnx. then i used the sample code in the [main page](https://github.com/lobe/lobe.NET#use-the-model-in-your-own-net-application) 
but it shows me an error on runtime:

System.**TypeInitializationException**
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.ML.OnnxRuntime.**NativeMethods**' threw an exception.
  Source=**Microsoft.ML.OnnxRuntime**
  StackTrace:
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in C:\a\3\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 50
   at lobe.OnnxImageClassifier.InitialiseFromSignature(Signature signature, String modelFileName)
   at lobe.ImageClassifier.CreateFromSignature(Signature signature, String modelFileName, String engineType)
   at lobe.ImageClassifier.CreateFromSignatureFile(FileInfo signatureFile, String modelFileName, String format)
   at AIWebApp.ML.LobeOfficeAppDetection.Main(String signatureFilePath, String imageToClassify) in G:\***\LobeDetection.cs:line 26   at ***.Tests.MyTests.Test1() in G:\***\MyTests.cs:line 21

Inner Exception 1:
**BadImageFormatException**: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Could you please help me to solve the  problem ? 
thanks in advanced
regards
mohammad

**Comment by mbs220** [comment]
i think this is where the exception thrown:
[https://github.com/microsoft/onnxruntime/blob/eab164e1a5cd7760ee653ffe455e7a10cded7cb2/csharp/src/Microsoft.ML.OnnxRuntime/InferenceSession.cs#L693](https://github.com/microsoft/onnxruntime/blob/eab164e1a5cd7760ee653ffe455e7a10cded7cb2/csharp/src/Microsoft.ML.OnnxRuntime/InferenceSession.cs#L693 )

**Comment by colombod** [comment]
hi, what is your environment? That seems to be a platform that the onnx runtimes do not cover.

**Comment by mbs220** [comment]
hi @colombod 
it's Windows 7 & 10

At [#6367](https://github.com/microsoft/onnxruntime/issues/6367) we discussed about it
